// Vocabulary data for quizzes
const vocabularyData = {
  "Công nghệ": [
    { word: "software", meaning: "phần mềm" },
    { word: "hardware", meaning: "phần cứng" },
    { word: "database", meaning: "cơ sở dữ liệu" },
    { word: "algorithm", meaning: "thuật toán" },
    { word: "interface", meaning: "giao diện" },
    { word: "server", meaning: "máy chủ" },
    { word: "network", meaning: "mạng" },
    { word: "protocol", meaning: "giao thức" },
    { word: "encryption", meaning: "mã hóa" },
    { word: "firewall", meaning: "tường lửa" },
    { word: "cloud", meaning: "đám mây" },
    { word: "API", meaning: "giao diện lập trình ứng dụng" },
    { word: "framework", meaning: "khung làm việc" },
    { word: "debug", meaning: "gỡ lỗi" },
    { word: "deploy", meaning: "triển khai" }
  ],
  "Kinh doanh": [
    { word: "stakeholder", meaning: "bên liên quan" },
    { word: "strategy", meaning: "chiến lược" },
    { word: "revenue", meaning: "doanh thu" },
    { word: "profit", meaning: "lợi nhuận" },
    { word: "budget", meaning: "ngân sách" },
    { word: "investment", meaning: "đầu tư" },
    { word: "market", meaning: "thị trường" },
    { word: "competition", meaning: "cạnh tranh" },
    { word: "partnership", meaning: "đối tác" },
    { word: "negotiation", meaning: "đàm phán" },
    { word: "contract", meaning: "hợp đồng" },
    { word: "brand", meaning: "thương hiệu" },
    { word: "marketing", meaning: "tiếp thị" },
    { word: "sales", meaning: "bán hàng" },
    { word: "customer", meaning: "khách hàng" }
  ],
  "Du lịch": [
    { word: "destination", meaning: "điểm đến" },
    { word: "itinerary", meaning: "lịch trình" },
    { word: "accommodation", meaning: "chỗ ở" },
    { word: "booking", meaning: "đặt chỗ" },
    { word: "reservation", meaning: "đặt trước" },
    { word: "tourist", meaning: "du khách" },
    { word: "guide", meaning: "hướng dẫn viên" },
    { word: "sightseeing", meaning: "tham quan" },
    { word: "landmark", meaning: "địa danh" },
    { word: "passport", meaning: "hộ chiếu" },
    { word: "visa", meaning: "thị thực" },
    { word: "luggage", meaning: "hành lý" },
    { word: "boarding", meaning: "lên máy bay" },
    { word: "departure", meaning: "khởi hành" },
    { word: "arrival", meaning: "đến nơi" }
  ],
  "Y tế": [
    { word: "diagnosis", meaning: "chẩn đoán" },
    { word: "treatment", meaning: "điều trị" },
    { word: "symptom", meaning: "triệu chứng" },
    { word: "prescription", meaning: "đơn thuốc" },
    { word: "medication", meaning: "thuốc" },
    { word: "surgery", meaning: "phẫu thuật" },
    { word: "recovery", meaning: "hồi phục" },
    { word: "patient", meaning: "bệnh nhân" },
    { word: "doctor", meaning: "bác sĩ" },
    { word: "nurse", meaning: "y tá" },
    { word: "hospital", meaning: "bệnh viện" },
    { word: "clinic", meaning: "phòng khám" },
    { word: "emergency", meaning: "khẩn cấp" },
    { word: "appointment", meaning: "cuộc hẹn" },
    { word: "checkup", meaning: "kiểm tra sức khỏe" }
  ]
}; 